name: 'dbt_transit'
version: '1.0.0'
config-version: 2

profile: 'dbt_transit'

model-paths: ["models"]
target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  dbt_transit:
    staging:
      +materialized: view
    intermediate:
      +materialized: view
    marts:
      +materialized: table
